#!/usr/bin/env python3
from pathlib import Path
import argparse,hashlib,json,re,subprocess,sys,zipfile
ROOT_DEFAULT=Path(__file__).resolve().parents[1]
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def txt(p): return Path(p).read_text(encoding='utf-8-sig')
def basis_runtime_path(root:Path,name:str)->Path:
    migrated=root/'bin'/name
    return migrated if migrated.is_file() else root/name
class S:
    def __init__(self): self.rows=[]
    def c(self,n,v,d=''): self.rows.append((n,bool(v),d))
    def has(self,n,t,x): self.c(n,x in t)
    def no(self,n,t,x): self.c(n,x not in t)
    def eq(self,n,a,b): self.c(n,a==b,f'{a!r}!={b!r}' if a!=b else '')
    def done(self):
        for n,o,d in self.rows: print(('PASS  ' if o else 'FAIL  ')+n+(f' [{d}]' if d and not o else ''))
        p=sum(o for _,o,_ in self.rows); print(f'\nTOTAL {p}/{len(self.rows)}'); return 0 if p==len(self.rows) else 1

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--root',type=Path,default=ROOT_DEFAULT); ap.add_argument('--basis-root',type=Path,required=True); ap.add_argument('--release-zip',type=Path); a=ap.parse_args()
    root=a.root.resolve(); basis=a.basis_root.resolve(); s=S()
    meta=json.loads((root/'bin/version.json').read_text(encoding='utf-8')); version=str(meta['version']); profile=str(meta.get('releaseProfile','patch'))
    markdown_validator=txt(root/'tools/validate_markdown_language.py')
    release_validator=txt(root/'tests/validate_release.py')
    s.has('LBS-18 permanent Markdown language validator scans markdown',markdown_validator,"root.rglob('*.md')")
    s.has('LBS-18 Markdown validator ignores fenced code',markdown_validator,'if in_fence:')
    s.has('LBS-18 Markdown validator preserves delimited literals',markdown_validator,'strip_literals')
    s.has('LBS-18 release gate invokes Markdown language validator',release_validator,'LBS-18 repository Markdown language gate passes')
    prepare_release=txt(root/'tools/prepare_release.py')
    s.has('LBS-18 release tooling retains English README version marker',prepare_release,'**Current development version:**')
    s.no('LBS-18 release tooling has no legacy German README version marker',prepare_release,'Aktueller Entwicklungsstand')
    s.c('LBS-15 protected intent is explicit',isinstance(meta.get('protectedFragmentIntent'),list))
    s.c('LBS-15 repository delete intent is explicit',isinstance(meta.get('repositoryDeleteIntent'),list))
    basis_tray=txt(basis_runtime_path(basis,'LenovoBootMenuTray.ps1')); tray=txt(root/'bin/LenovoBootMenuTray.ps1')
    bm=re.search(r"\$script:AppVersion = '([^']+)'",basis_tray); basis_version=bm.group(1) if bm else ''
    s.has('Generated runtime uses canonical version',tray,f"$script:AppVersion = '{version}'")
    app_template=txt(root/'src/App/LenovoBootMenuTray.template.ps1')
    s.has('v0.6.8.1 tray tooltip is product name only',app_template,"$script:TrayIcon.Text = 'Lenovo Boot Selector'")
    s.no('v0.6.8.1 legacy German tray-tooltip suffix removed',app_template,'Startziel wählen')
    s.c('LBS-10 active regression profile is version-only or patch',profile in {'version-only','patch'},profile)
    if profile=='version-only':
        normalized=tray.replace(f"$script:AppVersion = '{version}'",f"$script:AppVersion = '{basis_version}'",1)
        s.eq('Product runtime unchanged except injected version',normalized,basis_tray)
        for p in sorted((root/'src').rglob('*.ps1')):
            rel=p.relative_to(root).as_posix()
            s.eq(f'Product module byte-identical to basis: {rel}',sha(p),sha(basis/rel))
    for rel in ['Uninstall-LenovoBootMenuTasks.ps1','Start-LenovoBootMenuTray.cmd','Start-LenovoBootMenuTray.vbs','Uninstall-LenovoBootMenuTasks.cmd','LenovoBootMenuTray.ico','icon-preview.png']:
        s.eq(f'Runtime asset byte-identical to basis: {rel}',sha(root/'bin'/rel),sha(basis_runtime_path(basis,rel)))
    if profile=='version-only':
        s.eq('Installer byte-identical for non-product release',sha(root/'bin/Install-LenovoBootMenuTasks.ps1'),sha(basis_runtime_path(basis,'Install-LenovoBootMenuTasks.ps1')))
    ui=txt(root/'src/UI/UpdatePresentation.ps1'); infra=txt(root/'src/Infrastructure/UpdateClient.ps1'); transport=txt(root/'src/Infrastructure/UpdateTransport.ps1')
    refresh_ui=txt(root/'src/UI/RefreshPresentation.ps1'); popup_ui=txt(root/'src/UI/Popup.ps1')
    taskbroker=txt(root/'src/Infrastructure/TaskBroker.ps1'); install=txt(root/'bin/Install-LenovoBootMenuTasks.ps1'); diagnostics=txt(root/'src/Infrastructure/RuntimeDiagnostics.ps1'); update_runtime=txt(root/'src/Application/UpdateRuntime.ps1')
    diagnostics_init=diagnostics[diagnostics.find('function Initialize-RuntimeDiagnostics'):diagnostics.find('function Write-RuntimeDiagnosticEvent')]
    s.has('LBS-22 template preserves inherited diagnostics session input',app_template,'$script:InheritedRuntimeSessionId = [string]$RuntimeSessionId')
    s.has('LBS-22 diagnostics initialization uses captured inherited ID',diagnostics_init,'$candidate = ([string]$script:InheritedRuntimeSessionId).Trim()')
    s.has('LBS-22 parentSession reports inherited state only',diagnostics_init,'parentSession = $hasParentSession')
    s.has('LBS-17 update action remains manual and localized',ui,"-SecondaryButtonText (Get-LocalizedString -Key 'Update.InstallNow') -SecondaryAction { Start-ManualAppUpdate }")
    s.has('LBS-17 LBS-14 shared update dialog title uses canonical key',ui,"-Title (Get-LocalizedString -Key 'Update.Available')")
    s.has('LBS-17 LBS-14 header message remains localized through canonical key',refresh_ui,"Get-LocalizedString -Key 'Update.Available'")
    s.has('LBS-14 header interaction remains refresh-gated',refresh_ui,'Set-HeaderUpdateInteractionState -Enabled (-not $active -and $updateAvailable)')
    s.has('LBS-14 header hover uses Lenovo accent state',refresh_ui,'$script:HeaderStatusLabel.Focused')
    s.has('LBS-14 header control is a Button for native keyboard activation',popup_ui,'$headerSub = New-Object System.Windows.Forms.Button')
    s.has('LBS-14 header hover is tracked',popup_ui,'$script:HeaderStatusHovered = $true')
    s.has('LBS-14 header click is interaction-gated',popup_ui,'if (-not $script:HeaderUpdateInteractionEnabled) { return }')
    s.has('LBS-14 header click opens shared dialog',popup_ui,'[void](Show-AvailableUpdateDialog)')
    s.eq('LBS-14 popup contains one shared-dialog invocation',popup_ui.count('Show-AvailableUpdateDialog'),1)
    s.has('No periodic update polling remains',ui,'There is no periodic polling')
    s.has('LBS-21 popup-open automatic update mode retained',ui,"Start-UpdateCheckUiWorker -Mode 'Popup'")
    s.has('LBS-21 popup open triggers automatic version check',popup_ui,'[void](Start-PopupUpdateCheck)')
    s.no('LBS-21 process-once startup update state remains removed',update_runtime,'StartupCheckStarted')
    s.no('LBS-21 tray startup trigger remains removed',app_template,'Start-StartupUpdateCheck')
    s.has('Fixed GitHub source unchanged',transport,'SaschaP1980/LenovoBootSelector/main/downloads/latest.json')
    s.has('LBS-5 transport module owns WebClient creation',transport,'function New-LenovoWebClient')
    s.no('LBS-5 UpdateClient no longer creates WebClient directly',infra,'function New-LenovoWebClient')
    s.has('LBS-5 manifest network failure is structured',transport,"-Category 'network' -Stage 'manifest-download'")
    s.has('LBS-5 package network failure is structured',transport,"-Category 'network' -Stage 'package-download'")
    s.has('LBS-5 hash failure is separate from package failure',infra,"-Category 'hash' -Stage 'package-hash'")
    s.has('LBS-5 check worker returns failure stage',infra,"FailureStage=''")
    s.has('LBS-5 prepare UI propagates network status',ui,'networkStatus=$networkStatus')
    s.no('Updater remains unelevated',infra+'\n'+transport,'RunAs')
    s.no('Updater has no TaskBroker mutation',infra+'\n'+transport,'TaskBroker')
    s.no('Updater has no bcdedit',(infra+'\n'+transport).lower(),'bcdedit')
    s.has('LBS-6 TaskBroker schema is v0.2.13',tray,"$script:SupportedTaskBrokerVersions = @('0.2.13')")
    s.has('LBS-6 installer schema is v0.2.13',install,"$version = '0.2.13'")
    s.has('LBS-6 explicit metadata boundary contract retained',install,"boundaryContract = 'fixed-task-v1'")
    s.no('LBS-6 no free TaskName call reaches runtime runner',taskbroker.lower(),'invoke-authorizedtask -taskname')
    s.has('LBS-6 operation-only runtime runner retained',taskbroker,"[ValidateSet('ManagerRefresh','FirmwareRefresh','BootNext','DefaultSet','DefaultClear')]")
    s.has('LBS-6 strict metadata contract retained',taskbroker,'function Test-TaskBrokerMetadataContract')
    s.has('LBS-6 fixed task-name derivation retained',taskbroker,'function Get-TaskBrokerExpectedTargetTaskName')
    s.has('LBS-6 task ACL dangerous-rights rejection retained',install,'$dangerousMask')
    s.has('LBS-6 ProgramData ACL protection retained',install,'function Protect-TaskBrokerStateDirectory')
    s.has('LBS-6 metadata ACL protection retained',install,'function Protect-TaskBrokerMetadataFile')
    s.has('v0.6.4.1 ACL mutation predicate retained',install,'function Test-TaskBrokerRightsContainMutation')
    s.no('v0.6.4.1 broken composite Modify write-mask removed',install,'[System.Security.AccessControl.FileSystemRights]::Modify -bor')
    s.has('v0.6.4.1 state validator calls ACL mutation predicate',install,'Test-TaskBrokerRightsContainMutation -Rights $rights')
    s.has('v0.6.4.1 diagnostics separate physical presence',diagnostics,'$present = [bool](Test-TaskBrokerInstallationPresent)')
    s.has('v0.6.4.1 diagnostics separate metadata readability',diagnostics,'metadataReadable = $true')
    s.has('v0.6.4.1 diagnostics separate compatibility',diagnostics,'compatible = $compatible')
    s.c('LBS-6 security boundary documentation retained',(root/'docs/SECURITY_BOUNDARY.md').is_file())
    s.c('LBS-6 native boundary test retained',(root/'tests/Test-TaskBrokerBoundary.ps1').is_file())
    native_boundary=txt(root/'tests/Test-TaskBrokerBoundary.ps1')
    s.has('v0.6.4.1 native regression accepts ReadAndExecute',native_boundary,'ReadAndExecute is accepted as non-mutating')
    s.has('v0.6.4.1 native regression rejects Modify',native_boundary,'Modify is rejected as mutating')
    s.has('v0.6.4.1 native regression rejects FullControl',native_boundary,'FullControl is rejected as mutating')
    s.has('LBS-17 settings schema is v5',tray,'schemaVersion = 5')
    s.has('LBS-17 settings persist locale',tray,'locale = Resolve-LocaleIdCore -Locale $script:UiLocale')
    s.has('LBS-17 localization service is bundled',tray,'function Get-LocalizedString')
    language_ui=txt(root/'src/UI/LanguagePresentation.ps1')
    localization=txt(root/'src/Core/Localization.ps1')
    s.has('LBS-17 tray English language selector retained',app_template,"Set-LanguageFromUi -Locale 'en-US'")
    s.has('LBS-17 tray German language selector retained',app_template,"Set-LanguageFromUi -Locale 'de-DE'")
    s.has('LBS-17 language changes persist',language_ui,'Set-ActiveLocale -Locale $Locale -Persist')
    s.has('LBS-17 selected locale rebuilds popup',language_ui,'Rebuild-PopupForLocale')
    s.has('LBS-17 catalog keeps English default surface',localization,"'Tray.Open' = 'Open Lenovo Boot Selector'")
    s.has('LBS-17 catalog keeps German option surface',localization,"'Tray.Open' = 'Lenovo Boot Selector öffnen'")
    dialogs=txt(root/'src/UI/Dialogs.ps1')
    maintenance_ui=txt(root/'src/UI/MaintenancePresentation.ps1')
    diagnostics_ui=txt(root/'src/UI/DiagnosticsPresentation.ps1')
    startup_recovery=txt(root/'src/UI/StartupRecoveryDialog.ps1')
    s.has('LBS-17 maintenance dialog localization retained',dialogs,"Maintenance.Dialog.RemoveTitle")
    s.has('LBS-17 maintenance panel localization retained',maintenance_ui,"Maintenance.Panel.SetupHeading")
    s.has('LBS-17 diagnostics localization retained',diagnostics_ui,"Diagnostics.SavedTitle")
    s.has('LBS-17 startup recovery locale resolver retained',startup_recovery,'Get-StartupRecoveryLocale')
    s.c('LBS-17 localization remains before startup recovery',app_template.find('# @include src/Core/Localization.ps1') < app_template.find('# @include src/UI/StartupRecoveryDialog.ps1'))
    boot_entry_ui=txt(root/'src/UI/BootEntryList.ps1')
    s.has('LBS-17 template ready status remains localized',app_template,"Get-LocalizedString -Key 'Status.Ready'")
    s.has('LBS-17 template maintenance launch errors remain localized',app_template,"Get-LocalizedString -Key 'Maintenance.SetupNotStartedTitle'")
    s.has('LBS-17 entry visibility accessibility remains localized',boot_entry_ui,"Get-LocalizedString -Key 'Manage.HiddenAccessible'")
    s.no('LBS-17 update UI never exposes raw restart result text',ui,'-Message $resolved.Message')
    s.no('LBS-17 update UI never exposes raw worker exception text',ui,'-Message $_.Exception.Message')
    s.has('LBS-17 update installer helper receives localized failure prefix',ui,"Get-LocalizedString -Key 'Update.HelperFailurePrefix'")
    s.has('LBS-17 update installer helper transports localized text safely',infra,'-FailurePrefixBase64')
    s.no('LBS-17 installer fallback no longer hard-codes German visible failure prefix',infra,"Show-UpdateError ('Update fehlgeschlagen:")
    s.no('No permanent displayorder mutation',tray,"'/set', '{fwbootmgr}', 'displayorder'")
    for bad in ['SetFirmwareEnvironmentVariable','Lenovo_SetBiosSetting','Lenovo_SaveBiosSetting','Lenovo_SetFunctionRequest']:
        s.no(f'No firmware/WMI write path: {bad}',tray,bad)
    runtime_builder=txt(root/'tools/build_runtime.py')
    preflight=txt(root/'tools/candidate_preflight.py')
    release_verification=txt(root/'tools/release_verification.py')
    core_validator=txt(root/'tests/validate_core.py')
    candidate_workflow=txt(root/'.github/workflows/candidate-preflight.yml')
    release_workflow=txt(root/'.github/workflows/release.yml')
    windows_workflow=txt(root/'.github/workflows/windows-powershell51.yml')
    s.no('LBS-15 static runtime include registry remains removed',runtime_builder,'INCLUDES = [')
    s.has('LBS-15 template is runtime include source of truth',runtime_builder,'template_include_paths')
    s.has('LBS-15 candidate preflight remains executable',preflight,'CANDIDATE PREFLIGHT PASS')
    s.no('LBS-15 permanent protected frozen allowlist remains removed',core_validator,'INTENTIONALLY_CHANGED_FROZEN')
    s.has('LBS-15 core compares exact per-release protected delta',core_validator,'Per-release protected fragment intent exactly matches candidate delta')
    s.has('LBS-15 candidate workflow promotes exact SHA',candidate_workflow,'$GITHUB_SHA:refs/heads/$EXPECTED_RELEASE')
    s.has('LBS-15 candidate workflow explicitly dispatches release',candidate_workflow,'actions/workflows/release.yml/dispatches')
    s.has('LBS-20 Linux candidate gate remains explicit',candidate_workflow,'linux-preflight:')
    s.has('LBS-20 Windows candidate gate remains parallel reusable job',candidate_workflow,'uses: ./.github/workflows/windows-powershell51.yml')
    s.has('LBS-20 promotion remains dependency-aware',candidate_workflow,'needs:')
    s.has('LBS-20 exact Windows preflight status remains required',candidate_workflow,'preflight/windows-powershell51')
    s.has('LBS-20 candidate timing summary remains machine-readable',candidate_workflow,'CANDIDATE_TIMING_SUMMARY=')
    s.has('LBS-20 Windows workflow remains Windows-hosted',windows_workflow,'runs-on: windows-2025')
    s.has('LBS-20 Windows workflow remains PowerShell 5.1 guarded',windows_workflow,'Expected Windows PowerShell 5.1')
    s.has('LBS-20 Windows workflow retains native aggregate wrapper',windows_workflow,'Test-WindowsPowerShell51.ps1')
    s.has('LBS-20 Windows workflow retains manual benchmark dispatch',windows_workflow,'workflow_dispatch:')
    s.has('LBS-20 Windows summary remains machine-readable',windows_workflow,'WINDOWS_POWERSHELL51_SUMMARY=')
    s.has('LBS-15 release workflow supports workflow_dispatch',release_workflow,'workflow_dispatch:')
    s.has('LBS-15 release workflow requires green preflight',release_workflow,'Release SHA lacks successful preflight/candidate status.')
    s.has('LBS-20 release requires Linux preflight status',release_workflow,'Release SHA lacks successful preflight/linux status.')
    s.has('LBS-20 release requires Windows preflight status',release_workflow,'Release SHA lacks successful preflight/windows-powershell51 status.')
    s.has('LBS-16 candidate summary remains machine-readable',preflight,'CANDIDATE_PREFLIGHT_SUMMARY=')
    s.has('LBS-16 release summary remains machine-readable',release_verification,'RELEASE_VERIFICATION_SUMMARY=')
    s.has('LBS-16 release workflow retains aggregated verifier',release_workflow,'tools/release_verification.py')
    s.has('LBS-16 release summary retains eight-gate contract',release_verification,'EXPECTED_RELEASE_CONTEXTS')
    s.has('LBS-20 release summary retains three candidate-gate contract',release_verification,'EXPECTED_CANDIDATE_CONTEXTS')
    s.has('LBS-20 release summary exposes candidate gates',release_verification,"'candidateGates':candidate_gates")
    update_native=txt(root/'tests/Test-UpdateCore.ps1')
    mutex_native=txt(root/'tests/Test-SingleInstanceMutex.ps1')
    s.has('Native update test retains AST source-count self-audit',update_native,'[System.Management.Automation.Language.Parser]::ParseFile')
    s.has('Native update test retains explicit 62 runtime guard',update_native,'if ($checks -ne 62) { throw "Unexpected update test count $checks" }')
    s.has('Native mutex test retains explicit count guard',mutex_native,'if ($checks -ne 4) { throw "Unexpected mutex test count $checks" }')
    cp=subprocess.run([sys.executable,str(root/'tools/release_verification.py'),'--self-test'],capture_output=True,text=True); s.eq('LBS-16 release verification self-test',cp.returncode,0)
    cp=subprocess.run([sys.executable,str(root/'tools/build_runtime.py'),'--root',str(root),'--check'],capture_output=True,text=True); s.eq('Runtime deterministic',cp.returncode,0)
    cp=subprocess.run([sys.executable,str(root/'tools/build_catch_audit.py'),'--root',str(root),'--check'],capture_output=True,text=True); s.eq('Catch audit deterministic',cp.returncode,0)
    if a.release_zip:
        with zipfile.ZipFile(a.release_zip) as z:
            names=z.namelist(); s.eq('Release remains flat 10-file package',len(names),10); s.c('Release has no directories',all('/' not in n for n in names)); s.eq('Packaged runtime equals source runtime',z.read('LenovoBootMenuTray.ps1'),(root/'bin/LenovoBootMenuTray.ps1').read_bytes())
    return s.done()
if __name__=='__main__': raise SystemExit(main())
