#!/usr/bin/env python3
from pathlib import Path
import argparse,json,re,subprocess,sys
ROOT_DEFAULT=Path(__file__).resolve().parents[1]

def txt(p): return Path(p).read_text(encoding='utf-8-sig')
class S:
    def __init__(self): self.rows=[]
    def c(self,n,v,d=''): self.rows.append((n,bool(v),d))
    def has(self,n,t,x): self.c(n,x in t)
    def no(self,n,t,x): self.c(n,x not in t)
    def eq(self,n,a,b): self.c(n,a==b,f'{a!r}!={b!r}' if a!=b else '')
    def done(self):
        for n,o,d in self.rows: print(('PASS  ' if o else 'FAIL  ')+n+(f' [{d}]' if d and not o else ''))
        p=sum(o for _,o,_ in self.rows); print(f'\nTOTAL {p}/{len(self.rows)}'); return 0 if p==len(self.rows) else 1

def fn(src,name):
    m=re.search(rf'(?m)^function\s+{re.escape(name)}\b',src)
    if not m:return ''
    n=re.search(r'(?m)^function\s+[A-Za-z0-9_-]+\b',src[m.end():])
    e=m.end()+n.start() if n else len(src)
    return src[m.start():e]

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--root',type=Path,default=ROOT_DEFAULT); a=ap.parse_args(); root=a.root.resolve(); s=S()
    markdown_gate=root/'tools/validate_markdown_language.py'
    s.c('LBS-18 Markdown language validator exists',markdown_gate.is_file())
    markdown_cp=subprocess.run([sys.executable,'-B',str(markdown_gate),'--root',str(root)],capture_output=True,text=True) if markdown_gate.is_file() else None
    s.eq('LBS-18 repository Markdown language gate passes',markdown_cp.returncode if markdown_cp else 1,0)
    initial_prompt=txt(root/'docs/INITIAL_PROMPT.md') if (root/'docs/INITIAL_PROMPT.md').is_file() else ''
    github_howto=txt(root/'docs/GITHUB_HOWTO.md') if (root/'docs/GITHUB_HOWTO.md').is_file() else ''
    release_process=txt(root/'docs/RELEASE_PROCESS.md') if (root/'docs/RELEASE_PROCESS.md').is_file() else ''
    s.has('LBS-18 initial prompt declares English repository language',initial_prompt,'English is the canonical language for **all repository and durable GitHub documentation**.')
    s.has('LBS-18 GitHub how-to declares English repository language',github_howto,'English is the canonical language for repository and durable GitHub documentation.')
    s.has('LBS-18 release process declares English repository language',release_process,'English is the canonical language for repository and durable GitHub documentation.')
    prepare_release=txt(root/'tools/prepare_release.py')
    s.has('LBS-18 prepare_release uses English README version marker',prepare_release,'**Current development version:**')
    s.no('LBS-18 prepare_release no longer depends on German README version marker',prepare_release,'Aktueller Entwicklungsstand')
    vp=root/'bin/version.json'; s.c('Canonical bin/version.json exists',vp.is_file())
    meta={}
    if vp.is_file():
        try: meta=json.loads(vp.read_text(encoding='utf-8'))
        except Exception: meta={}
    version=str(meta.get('version','')); profile=str(meta.get('releaseProfile','')); schema=meta.get('schemaVersion')
    s.c('Canonical version schema is v2',schema==2,schema)
    s.c('Canonical version input excludes publishedUtc','publishedUtc' not in meta)
    s.c('Canonical version is four numeric components',bool(re.fullmatch(r'\d+\.\d+\.\d+\.\d+',version)),version)
    s.c('Release profile declared',profile in {'version-only','patch'},profile)
    protected_intent=meta.get('protectedFragmentIntent')
    delete_intent=meta.get('repositoryDeleteIntent')
    s.c('LBS-15 protectedFragmentIntent is explicit list',isinstance(protected_intent,list))
    s.c('LBS-15 protectedFragmentIntent has unique strings',isinstance(protected_intent,list) and len(protected_intent)==len(set(protected_intent)) and all(isinstance(x,str) and x for x in protected_intent))
    s.c('LBS-15 repositoryDeleteIntent is explicit list',isinstance(delete_intent,list))
    s.c('LBS-15 repositoryDeleteIntent has unique strings',isinstance(delete_intent,list) and len(delete_intent)==len(set(delete_intent)) and all(isinstance(x,str) and x for x in delete_intent))
    runtime_names=['BUILD_INTEGRITY.txt','icon-preview.png','Install-LenovoBootMenuTasks.ps1','LenovoBootMenuTray.ico','LenovoBootMenuTray.ps1','Start-LenovoBootMenuTray.cmd','Start-LenovoBootMenuTray.vbs','Uninstall-LenovoBootMenuTasks.cmd','Uninstall-LenovoBootMenuTasks.ps1','version.json']
    for name in runtime_names:
        s.c(f'LBS-2 runtime/project file moved to bin: {name}',(root/'bin'/name).is_file())
        s.c(f'LBS-2 obsolete root path removed: {name}',not (root/name).exists())
    s.c('README remains repository-root file',(root/'README.md').is_file())
    s.c('CHANGELOG remains repository-root file',(root/'CHANGELOG.md').is_file())
    s.c('Git control file remains at repository root',(root/'.gitignore').is_file())
    s.c('LBS-1 canonical architecture baseline moved to docs/architecture',(root/'docs/architecture/ARCHITECTURE_BASELINE.json').is_file())
    s.c('LBS-1 canonical catch audit moved to audits',(root/'audits/CATCH_AUDIT.json').is_file())
    s.c('LBS-1 root has no architecture baseline JSONs',not any(root.glob('ARCHITECTURE_BASELINE*.json')))
    s.c('LBS-1 root has no catch audit JSONs',not any(root.glob('CATCH_AUDIT*.json')))
    s.c('LBS-1 historical architecture baselines retained',len(list((root/'docs/architecture').glob('ARCHITECTURE_BASELINE_v*.json'))) >= 1)
    s.c('LBS-1 historical catch audits retained',len(list((root/'audits').glob('CATCH_AUDIT_v*.json'))) >= 1)
    s.c('LBS-13 active tests README exists',(root/'tests/README.md').is_file())
    s.c('LBS-13 historical tests README exists',(root/'tests-history/README.md').is_file())
    s.c('LBS-13 no versioned validators remain in active tests',not any((root/'tests').glob('validate_v*.py')))
    historical_validators=sorted((root/'tests-history').glob('*.py')) if (root/'tests-history').is_dir() else []
    historical_pattern=re.compile(r'^(release|core|boundary|regression)-v\d+\.\d+\.\d+(?:\.\d+)?\.py$')
    s.c('LBS-13 historical validators use category plus readable version',bool(historical_validators) and all(historical_pattern.fullmatch(x.name) for x in historical_validators),[x.name for x in historical_validators if not historical_pattern.fullmatch(x.name)])
    historical_categories={x.name.split('-v',1)[0] for x in historical_validators}
    s.eq('LBS-13 all historical test categories retained',historical_categories,{'release','core','boundary','regression'})
    s.eq('LBS-13 historical validator count retained',len(historical_validators),74)
    # Native harness count contracts: protect against silent assertion-count drift.
    update_test=txt(root/'tests/Test-UpdateCore.ps1')
    update_assertion_calls=0
    for line in update_test.splitlines():
        if re.match(r'\s*function\s+Assert-(?:True|Equal)\b',line,re.I):
            continue
        update_assertion_calls += len(re.findall(r'(?:^|;\s*)Assert-(?:True|Equal)\b',line))
    s.eq('Update native test has exact 62 assertion call sites',update_assertion_calls,62)
    s.has('Update native test self-audits source via PowerShell AST',update_test,'[System.Management.Automation.Language.Parser]::ParseFile')
    s.has('Update native test derives command names from AST',update_test,'$node.GetCommandName()')
    s.has('Update native test compares executed and source assertion counts',update_test,'if ($checks -ne $sourceAssertionCount)')
    s.has('Update native test keeps explicit source coverage guard 62',update_test,'if ($sourceAssertionCount -ne 62) { throw "Unexpected update assertion source count $sourceAssertionCount" }')
    s.has('Update native test keeps explicit runtime coverage output 62',update_test,'Write-Host "UPDATE TOTAL $checks/62"')
    s.has('Update native test keeps explicit runtime coverage guard 62',update_test,'if ($checks -ne 62) { throw "Unexpected update test count $checks" }')
    mutex_test=txt(root/'tests/Test-SingleInstanceMutex.ps1')
    s.has('Mutex native test keeps explicit total output',mutex_test,'Write-Host "MUTEX TOTAL $checks/4"')
    s.has('Mutex native test fails closed on count drift',mutex_test,'if ($checks -ne 4) { throw "Unexpected mutex test count $checks" }')
    tray=txt(root/'bin/LenovoBootMenuTray.ps1') if (root/'bin/LenovoBootMenuTray.ps1').is_file() else ''
    template=txt(root/'src/App/LenovoBootMenuTray.template.ps1')
    expected=f"$script:AppVersion = '{version}'"
    s.has('Generated runtime uses canonical version',tray,expected)
    s.eq('Generated runtime version declaration exactly once',tray.count(expected),1)
    s.eq('Template has exactly one version injection token',template.count('@APP_VERSION@'),1)
    s.no('Template no longer hard-codes concrete AppVersion',template,"$script:AppVersion = '0.5.")
    for rel in ['tools/build_packages.py','tools/build_transition.py','tools/build_catch_audit.py']:
        t=txt(root/rel)
        s.no(f'{rel} has no hard-coded VERSION constant',t,"VERSION='")
        s.has(f'{rel} uses release_common version source',t,'release_common')
    s.c('Persistent prepare_release tool exists',(root/'tools/prepare_release.py').is_file())
    s.c('LBS-15 candidate preflight tool exists',(root/'tools/candidate_preflight.py').is_file())
    s.c('LBS-15 protected fragment helper exists',(root/'tools/protected_fragments.py').is_file())
    verification_path=root/'tools/release_verification.py'
    s.c('LBS-16 release verification helper exists',verification_path.is_file())
    prepare=txt(root/'tools/prepare_release.py') if (root/'tools/prepare_release.py').is_file() else ''
    common=txt(root/'tools/release_common.py') if (root/'tools/release_common.py').is_file() else ''
    candidate_preflight=txt(root/'tools/candidate_preflight.py') if (root/'tools/candidate_preflight.py').is_file() else ''
    release_verification=txt(verification_path) if verification_path.is_file() else ''
    runtime_builder=txt(root/'tools/build_runtime.py')
    s.has('Prepare tool accepts explicit publication timestamp',prepare,"ap.add_argument('--published-utc')")
    s.has('Prepare tool rejects missing schema-v2 publication timestamp',prepare,'publishedUtc must be supplied explicitly for schemaVersion 2')
    s.has('Release config keeps legacy schema 1 readable',common,"schema not in {1,2}")
    s.has('Release config forbids publishedUtc in schema 2',common,'schemaVersion 2 must not contain publishedUtc')
    s.has('LBS-10 active release profiles are exactly version-only and patch',common,"VALID_PROFILES = {'version-only','patch'}")
    s.no('LBS-10 historical architecture profile is not active in release config',common,"'release-architecture'")
    s.has('LBS-15 release config validates protected intent',common,'protectedFragmentIntent must be an array of non-empty strings')
    s.has('LBS-15 release config validates delete intent',common,'repositoryDeleteIntent must be an array of non-empty strings')
    s.has('LBS-15 preflight runs release validator',candidate_preflight,'tests/validate_release.py')
    s.has('LBS-15 preflight runs core validator with basis',candidate_preflight,"'--basis-root',str(basis)")
    s.has('LBS-15 preflight runs boundary validator',candidate_preflight,'tests/validate_boundary.py')
    s.has('LBS-15 preflight runs regression validator',candidate_preflight,'tests/validate_regression.py')
    s.has('LBS-15 preflight checks protected intent exact delta',candidate_preflight,'protectedFragmentIntent mismatch')
    s.has('LBS-15 preflight checks repository delete intent exact delta',candidate_preflight,'repositoryDeleteIntent mismatch')
    s.has('LBS-15 preflight rejects historical ZIP changes',candidate_preflight,'candidate must not modify historical release ZIPs')
    s.has('LBS-16 candidate preflight emits machine-readable summary',candidate_preflight,'CANDIDATE_PREFLIGHT_SUMMARY=')
    s.has('LBS-16 release verification emits machine-readable summary',release_verification,'RELEASE_VERIFICATION_SUMMARY=')
    s.has('LBS-16 release verification owns exact eight contexts',release_verification,"'release/tag'")
    s.has('LBS-16 release verification checks candidate cleanup',release_verification,"candidateDeleted")
    s.has('LBS-16 release verification checks release cleanup',release_verification,"releaseDeleted")
    s.has('LBS-16 release verification checks latest metadata',release_verification,"downloads/latest.json")
    s.has('LBS-16 release verification checks source tree ZIP freedom',release_verification,"source tree contains ZIP file")
    s.has('LBS-16 release verification checks source tree cache freedom',release_verification,"source tree contains Python cache artifact")
    s.has('LBS-16 release verification writes GitHub job summary',release_verification,'GITHUB_STEP_SUMMARY')
    if verification_path.is_file():
        cp=subprocess.run([sys.executable,str(verification_path),'--self-test'],capture_output=True,text=True)
        s.eq('LBS-16 release verification helper self-test passes',cp.returncode,0)
        s.has('LBS-16 helper self-test confirms pass',cp.stdout,'PASS release verification helper self-test')
    s.no('LBS-15 runtime builder has no static INCLUDES registry',runtime_builder,'INCLUDES = [')
    s.has('LBS-15 runtime builder derives includes from template',runtime_builder,'def template_include_paths')
    s.has('LBS-15 runtime builder rejects duplicate includes',runtime_builder,'duplicate runtime include marker')
    s.has('LBS-15 runtime builder rejects missing include files',runtime_builder,'runtime include file missing')
    s.c('Canonical catch audit exists under audits/',(root/'audits/CATCH_AUDIT.json').is_file())
    s.c('Canonical architecture baseline exists under docs/architecture/',(root/'docs/architecture/ARCHITECTURE_BASELINE.json').is_file())
    s.c('Persistent release workflow exists',(root/'.github/workflows/release.yml').is_file())
    s.c('LBS-15 persistent candidate preflight workflow exists',(root/'.github/workflows/candidate-preflight.yml').is_file())
    s.c('LBS-20 Windows PowerShell 5.1 workflow exists',(root/'.github/workflows/windows-powershell51.yml').is_file())
    s.c('No redundant PR verification workflow exists',not (root/'.github/workflows/release-pr.yml').exists())
    if (root/'.github/workflows/candidate-preflight.yml').is_file():
        cw=txt(root/'.github/workflows/candidate-preflight.yml')
        s.has('LBS-15 candidate workflow targets candidate branch family',cw,'candidate/**')
        s.has('LBS-15 candidate workflow runs exact preflight tool',cw,'tools/candidate_preflight.py')
        s.has('LBS-15 candidate workflow writes preflight status',cw,"context='preflight/candidate'")
        s.has('LBS-15 candidate workflow creates release ref only after preflight',cw,'refs/heads/$EXPECTED_RELEASE')
        s.has('LBS-15 candidate workflow has actions write for explicit handoff',cw,'actions: write')
        s.has('LBS-15 candidate workflow explicitly dispatches release workflow',cw,'actions/workflows/release.yml/dispatches')
        s.has('LBS-15 candidate workflow rolls back release ref if dispatch fails',cw,'git push origin --delete "$EXPECTED_RELEASE"')
        s.has('LBS-15 candidate workflow removes candidate branch after promotion',cw,'git push origin --delete "$GITHUB_REF_NAME"')
        s.has('LBS-20 candidate workflow has parallel Linux job',cw,'linux-preflight:')
        s.has('LBS-20 candidate workflow calls Windows reusable workflow',cw,'uses: ./.github/workflows/windows-powershell51.yml')
        s.has('LBS-20 promotion waits for Linux and Windows',cw,'- windows-powershell51')
        s.has('LBS-20 aggregate preflight requires exact Linux status',cw,'preflight/linux')
        s.has('LBS-20 aggregate preflight requires exact Windows status',cw,'preflight/windows-powershell51')
        s.has('LBS-20 candidate workflow emits timing summary',cw,'CANDIDATE_TIMING_SUMMARY=')
        s.has('LBS-20 candidate workflow records always policy for benchmark release',cw,"'policy':'always'")
    if (root/'.github/workflows/release.yml').is_file():
        w=txt(root/'.github/workflows/release.yml')
        s.has('Release workflow targets one release branch family',w,'release/**')
        s.has('LBS-15 release workflow supports explicit dispatch',w,'workflow_dispatch:')
        s.has('Release workflow captures GitHub publication timestamp',w,"PUBLISHED_UTC=$(date -u +'%Y-%m-%dT%H:%M:%SZ')")
        s.eq('Release workflow has exactly two deterministic prepare-release rebuilds',w.count('python3 -B tools/prepare_release.py --root . --output-dir'),2)
        s.eq('Release workflow passes publication timestamp to both prepare-release rebuilds',w.count('tools/prepare_release.py --root . --output-dir /tmp/lbs-release --published-utc "$PUBLISHED_UTC"') + w.count('tools/prepare_release.py --root . --output-dir /tmp/lbs-release-check --published-utc "$PUBLISHED_UTC"'),2)
        s.has('Release workflow uses Python no-bytecode mode',w,'python3 -B tools/prepare_release.py')
        s.has('Release workflow disables child-process bytecode writes',w,"PYTHONDONTWRITEBYTECODE: '1'")
        s.has('Release workflow can create PRs',w,'pull-requests: write')
        s.has('Release workflow creates exactly one PR',w,'gh pr create')
        s.has('Release workflow writes final-head gate statuses',w,'statuses/$FINAL_SHA')
        s.has('Release workflow runs permanent release validator',w,'tests/validate_release.py')
        s.has('Release workflow runs permanent core validator',w,'tests/validate_core.py')
        s.has('LBS-15 release workflow requires preflight candidate status',w,'preflight/candidate')
        s.has('LBS-20 release workflow requires Linux candidate gate',w,'preflight/linux')
        s.has('LBS-20 release workflow requires Windows PowerShell gate',w,'preflight/windows-powershell51')
        s.has('LBS-15 release workflow rejects stale candidate main ancestry',w,'git merge-base --is-ancestor origin/main HEAD')
        s.has('LBS-15 release core gate compares previous source basis',w,'tests/validate_core.py --root . --basis-root /tmp/lbs-basis')
        s.has('Release workflow runs permanent boundary validator',w,'tests/validate_boundary.py')
        s.has('Release workflow runs permanent regression validator',w,'tests/validate_regression.py')
        s.has('LBS-16 release workflow records reproducibility marker',w,'/tmp/lbs-release/reproducible.ok')
        s.has('LBS-16 release workflow runs aggregated post-release verification',w,'tools/release_verification.py')
        s.has('LBS-16 release workflow passes candidate SHA into verification',w,'--candidate-sha "$CANDIDATE_SHA"')
        s.has('LBS-16 release workflow passes final PR head into verification',w,'--final-sha "$FINAL_SHA"')
        s.has('Release workflow creates tag only after PR creation',w,'Tag only after all gates and successful PR creation')
        s.has('Release workflow merges and deletes release branch',w,'gh pr merge')
        s.no('Release workflow is not version-specific',w,'0.5.10.0')
        s.no('Release workflow has no Base64 patch transport',w,'base64')
        s.no('Release workflow has no source helper branch',w,'source-v')
        s.no('Release workflow has no post-merge finalizer',w,'finalize')
        s.has('Release workflow allows only exact one-time LBS-2 root migration deletes',w,'EXPECTED_LBS2_DELETIONS')
        s.has('LBS-2 delete compatibility is gated by legacy root version',w,'origin/main:version.json')
        s.has('LBS-2 delete compatibility requires missing migrated version on main',w,'origin/main:bin/version.json')
        s.has('LBS-2 delete comparison disables rename detection',w,'--diff-filter=D --no-renames origin/main')
        s.has('Release workflow has one-time LBS-1 migration gate',w,'EXPECTED_LBS1_DELETIONS')
        s.has('LBS-1 migration requires legacy architecture root file',w,'origin/main:ARCHITECTURE_BASELINE.json')
        s.has('LBS-1 migration requires legacy catch-audit root file',w,'origin/main:CATCH_AUDIT.json')
        s.has('LBS-1 migration checks architecture target path',w,'docs/architecture/$path')
        s.has('LBS-1 migration checks audit target path',w,'audits/$path')
        s.has('Release workflow has one-time LBS-13 test-history migration gate',w,'EXPECTED_LBS13_DELETIONS')
        s.has('LBS-13 migration is gated by legacy versioned test path',w,'origin/main:tests/validate_v040.py')
        s.has('LBS-13 migration verifies byte-identical historical blobs',w,'LBS-13 historical validator blob missing')
        s.has('LBS-13 migration scans the committed historical tree',w,'git ls-tree -r HEAD tests-history')
    windows_workflow=root/'.github/workflows/windows-powershell51.yml'
    if windows_workflow.is_file():
        ww=txt(windows_workflow)
        s.has('LBS-20 Windows workflow supports reusable calls',ww,'workflow_call:')
        s.has('LBS-20 Windows workflow supports manual benchmarks',ww,'workflow_dispatch:')
        s.has('LBS-20 Windows workflow uses hosted Windows 2025 runner',ww,'runs-on: windows-2025')
        s.has('LBS-20 Windows workflow forces Windows PowerShell shell',ww,'shell: powershell')
        s.has('LBS-20 Windows workflow verifies PowerShell 5.1',ww,'Expected Windows PowerShell 5.1')
        s.has('LBS-20 Windows workflow regenerates deterministic runtime',ww,'tools/build_runtime.py --root .')
        s.has('LBS-20 Windows workflow checks deterministic runtime',ww,'tools/build_runtime.py --root . --check')
        s.has('LBS-20 Windows workflow executes aggregate native wrapper',ww,'Test-WindowsPowerShell51.ps1')
        s.has('LBS-20 Windows workflow publishes dedicated status',ww,'preflight/windows-powershell51')
        s.has('LBS-20 Windows workflow emits machine-readable summary',ww,'WINDOWS_POWERSHELL51_SUMMARY=')
        s.has('LBS-20 Windows workflow reports setup timing',ww,'setupMs')
        s.has('LBS-20 Windows workflow reports runtime preparation timing',ww,'runtimePreparationMs')
        s.has('LBS-20 Windows workflow reports test timing',ww,'testMs')
        s.has('LBS-20 Windows workflow verifies exact checkout SHA',ww,'Windows checkout SHA mismatch')

    for rel in ['tests/validate_release.py','tests/validate_core.py','tests/validate_boundary.py','tests/validate_regression.py']:
        s.c(f'Permanent validator exists: {rel}',(root/rel).is_file())
    default_ui=txt(root/'src/UI/DefaultTargetPresentation.ps1'); popup_ui=txt(root/'src/UI/Popup.ps1')
    s.has('LBS-17 default target startup check is localized',default_ui,"Get-LocalizedString -Key 'Status.Checking'")
    s.has('Default target pending state is limited to compatible metadata plus unknown readiness',default_ui,'$checking = ($schemaReady -and $null -eq $script:TaskBrokerReadyCached)')
    s.has('Default target pending state stays visually readable',default_ui,'$visualEnabled = ($enabled -or $checking)')
    s.has('Default target interaction remains separately gated',default_ui,'$script:DefaultInteractionEnabled = $enabled')
    s.has('Default target chevron is hidden only while checking',default_ui,'$script:DefaultArrowLabel.Visible = -not $checking')
    s.has('Popup default target click uses interaction gate',popup_ui,'if ($script:DefaultInteractionEnabled -and $script:DefaultButton)')
    s.has('Popup stores default target arrow for state updates',popup_ui,'$script:DefaultArrowLabel = $defaultArrow')
    ui=txt(root/'src/UI/UpdatePresentation.ps1'); infra=txt(root/'src/Infrastructure/UpdateClient.ps1'); transport=txt(root/'src/Infrastructure/UpdateTransport.ps1')
    complete=fn(ui,'Complete-UpdateCheck')
    available_dialog=fn(ui,'Show-AvailableUpdateDialog')
    manual=fn(ui,'Start-ManualUpdateCheck')
    popup_check=fn(ui,'Start-PopupUpdateCheck')
    check_worker=fn(ui,'Start-UpdateCheckUiWorker')
    popup_toggle=fn(popup_ui,'Show-OrTogglePopup')
    template=txt(root/'src/App/LenovoBootMenuTray.template.ps1')
    refresh_ui=txt(root/'src/UI/RefreshPresentation.ps1')
    header_visual=fn(refresh_ui,'Update-HeaderStatusInteractionVisual')
    header_interaction=fn(refresh_ui,'Set-HeaderUpdateInteractionState')
    popup_form=fn(popup_ui,'New-PopupForm')
    update_runtime=txt(root/'src/Application/UpdateRuntime.ps1')
    s.has('LBS-17 manual update button is localized',available_dialog,"-SecondaryButtonText (Get-LocalizedString -Key 'Update.InstallNow')")
    s.has('Manual update button still reuses manual update path',available_dialog,'Start-ManualAppUpdate')
    s.has('Manual update check reuses shared available dialog',complete,'Show-AvailableUpdateDialog')
    s.has('LBS-21 popup check reuses read-only hidden worker',popup_check,"Start-UpdateCheckUiWorker -Mode 'Popup'")
    s.no('LBS-21 popup check has no process-once startup gate',popup_check,'StartupCheckStarted')
    s.has('LBS-21 update worker rejects competing update operations',check_worker,'Test-UpdateRuntimeBusy -State $script:UpdateState')
    s.has('LBS-21 popup open triggers automatic update check',popup_toggle,'[void](Start-PopupUpdateCheck)')
    s.eq('LBS-21 popup open contains one automatic update trigger',popup_toggle.count('Start-PopupUpdateCheck'),1)
    s.has('LBS-21 visible popup hide returns before automatic check',popup_toggle,"if ($script:Popup.Visible) {\n        $script:Popup.Hide()\n        return\n    }")
    s.has('LBS-21 popup keeps fresh boot-target refresh',popup_toggle,'Start-BackgroundBootRefresh')
    s.no('LBS-21 tray startup automatic update trigger removed',template,'Start-StartupUpdateCheck')
    s.no('LBS-21 update runtime has no process-once startup gate',update_runtime,'StartupCheckStarted')
    s.no('LBS-21 update runtime has no startup completion flag',update_runtime,'StartupCheckCompleted')
    s.has('LBS-21 automatic popup check suppresses update dialogs',complete,'if (-not $isPopup)')
    s.has('LBS-21 popup completion has dedicated diagnostics',complete,'POPUP_UPDATE_CHECK_COMPLETED')
    s.has('LBS-17 header update-available message is localized',refresh_ui,"Get-LocalizedString -Key 'Update.Available'")
    s.has('Header keeps boot refresh as first update-status branch',refresh_ui,"if ($active) {")
    s.has('LBS-17 header boot refresh text is localized',refresh_ui,"Get-LocalizedString -Key 'Header.Refreshing'")
    s.has('Header restores update state after refresh',refresh_ui,"elseif ($updateAvailable)")
    s.has('LBS-14 header status uses focusable button control',popup_form,'$headerSub = New-Object System.Windows.Forms.Button')
    s.has('LBS-14 header button documents native Enter/Space activation',popup_form,'native Enter/Space activation')
    s.has('LBS-14 hover enters interactive visual state',popup_form,'$script:HeaderStatusHovered = $true')
    s.has('LBS-14 hover leave clears interactive visual state',popup_form,'$script:HeaderStatusHovered = $false')
    s.has('LBS-14 click is gated by update interaction state',popup_form,'if (-not $script:HeaderUpdateInteractionEnabled) { return }')
    s.has('LBS-14 click opens shared available-update dialog',popup_form,'[void](Show-AvailableUpdateDialog)')
    s.eq('LBS-14 shared dialog is invoked only from header click in popup form',popup_form.count('Show-AvailableUpdateDialog'),1)
    language_ui=txt(root/'src/UI/LanguagePresentation.ps1')
    localization=txt(root/'src/Core/Localization.ps1')
    s.has('LBS-17 tray exposes English selector',template,"Set-LanguageFromUi -Locale 'en-US'")
    s.has('LBS-17 tray exposes German selector',template,"Set-LanguageFromUi -Locale 'de-DE'")
    s.has('LBS-17 language selector persists through active locale service',language_ui,'Set-ActiveLocale -Locale $Locale -Persist')
    s.has('LBS-17 language change rebuilds visible popup',language_ui,'Rebuild-PopupForLocale')
    s.has('LBS-17 popup strings consume localization API',popup_ui,"Get-LocalizedString -Key 'Popup.NextBootSection'")
    s.has('LBS-17 English catalog exposes tray maintenance',localization,"'Tray.Maintenance' = 'Maintenance'")
    s.has('LBS-17 German catalog exposes tray maintenance',localization,"'Tray.Maintenance' = 'Wartung'")
    dialogs=txt(root/'src/UI/Dialogs.ps1')
    maintenance_ui=txt(root/'src/UI/MaintenancePresentation.ps1')
    diagnostics_ui=txt(root/'src/UI/DiagnosticsPresentation.ps1')
    startup_recovery=txt(root/'src/UI/StartupRecoveryDialog.ps1')
    s.has('LBS-17 maintenance dialog is localized',dialogs,"Get-LocalizedString -Key 'Maintenance.Dialog.RemoveTitle'")
    s.has('LBS-17 restart dialog is localized',dialogs,"Get-LocalizedString -Key 'Restart.Question'")
    s.has('LBS-17 maintenance panel is localized',maintenance_ui,"Get-LocalizedString -Key 'Maintenance.Panel.SetupHeading'")
    s.has('LBS-17 update dialog is localized',ui,"Get-LocalizedString -Key 'Update.AvailableMessage'")
    s.has('LBS-17 diagnostics dialog is localized',diagnostics_ui,"Get-LocalizedString -Key 'Diagnostics.SavedTitle'")
    s.has('LBS-17 startup recovery resolves persisted locale',startup_recovery,'Get-StartupRecoveryLocale')
    s.has('LBS-17 startup recovery uses pure localization core',startup_recovery,"Get-LocalizedStringCore -Key 'Startup.FailedTitle'")
    s.c('LBS-17 localization is included before startup recovery',template.find('# @include src/Core/Localization.ps1') < template.find('# @include src/UI/StartupRecoveryDialog.ps1'))
    s.has('LBS-14 interactive header uses hand cursor',header_visual,'[System.Windows.Forms.Cursors]::Hand')
    s.has('LBS-14 interactive header participates in tab navigation',header_visual,'$script:HeaderStatusLabel.TabStop = $interactive')
    s.has('LBS-14 keyboard focus uses Lenovo accent',header_visual,'$script:HeaderStatusLabel.Focused')
    s.has('LBS-14 refresh disables header update interaction',refresh_ui,'Set-HeaderUpdateInteractionState -Enabled (-not $active -and $updateAvailable)')
    s.has('LBS-14 maintenance disables header update interaction',refresh_ui,'Set-HeaderUpdateInteractionState -Enabled $false')
    s.has('LBS-17 LBS-14 shared dialog title uses canonical localization key',available_dialog,"-Title (Get-LocalizedString -Key 'Update.Available')")
    s.has('LBS-14 shared dialog uses already validated manifest',available_dialog,'$script:UpdateState.AvailableManifest')
    s.no('LBS-14 shared dialog starts no new update worker',available_dialog,'Start-UpdateCheckUiWorker')
    s.has('No periodic update polling policy retained',ui,'There is no periodic polling')
    s.has('Manual update check remains explicit menu action',template,'$updateCheckItem.Add_Click({ Start-ManualUpdateCheck })')
    s.c('LBS-5 transport module exists',(root/'src/Infrastructure/UpdateTransport.ps1').is_file())
    s.eq('LBS-5 transport include marker exactly once',template.count('# @include src/Infrastructure/UpdateTransport.ps1'),1)
    s.has('Fixed GitHub update source retained',transport,'SaschaP1980/LenovoBootSelector/main/downloads/latest.json')
    s.has('LBS-5 manifest transport is explicitly classified',transport,"-Category 'network' -Stage 'manifest-download'")
    s.has('LBS-5 package transport is explicitly classified',transport,"-Category 'network' -Stage 'package-download'")
    s.has('LBS-5 network status is preserved',transport,'NetworkStatus=$networkStatus')
    s.has('LBS-5 worker result exposes error category',infra,"ErrorCategory=''")
    s.has('LBS-5 hash failures use separate category',infra,"-Category 'hash' -Stage 'package-hash'")
    s.has('LBS-5 installer result persists failure category',infra,'failureCategory=[string]$failureCategory')
    s.has('LBS-5 restart failures are distinct',infra,"$failureCategory='restart'; $failureStage='restart-after-install'")
    s.has('LBS-5 UI diagnostics propagate worker category',ui,'errorCategory=$failureCategory')
    s.no('Updater remains unelevated',infra+'\n'+transport,'RunAs')
    s.no('Updater has no TaskBroker mutation',infra+'\n'+transport,'TaskBroker')
    s.no('Updater has no bcdedit',(infra+'\n'+transport).lower(),'bcdedit')

    taskbroker=txt(root/'src/Infrastructure/TaskBroker.ps1')
    installer=txt(root/'bin/Install-LenovoBootMenuTasks.ps1')
    diagnostics=txt(root/'src/Infrastructure/RuntimeDiagnostics.ps1')
    diagnostics_init=fn(diagnostics,'Initialize-RuntimeDiagnostics')
    refresh_native=txt(root/'tests/Test-RefreshRuntime.ps1')
    inherited_capture='$script:InheritedRuntimeSessionId = [string]$RuntimeSessionId'
    active_reset='$script:RuntimeSessionId = $null'
    s.c('LBS-22 inherited runtime session is captured before active diagnostics reset',template.find(inherited_capture)>=0 and template.find(active_reset)>template.find(inherited_capture))
    s.has('LBS-22 diagnostics initialization consumes captured inherited session',diagnostics_init,'$candidate = ([string]$script:InheritedRuntimeSessionId).Trim()')
    s.has('LBS-22 parent-session flag is captured before fresh ID generation',diagnostics_init,'$hasParentSession = [bool]$candidate')
    s.has('LBS-22 diagnostics event uses genuine inherited-session flag',diagnostics_init,'parentSession = $hasParentSession')
    s.has('LBS-22 native refresh suite covers all child roles',refresh_native,'All three child roles share one parent diagnostics log')
    s.has('LBS-22 native refresh suite retains 28-check guard',refresh_native,'if ($checks -ne 28) { throw "Expected 28 refresh checks, got $checks" }')
    state_acl=fn(installer,'Test-TaskBrokerStatePathLeastPrivilege')
    rights_predicate=fn(installer,'Test-TaskBrokerRightsContainMutation')
    broker_summary=fn(diagnostics,'Get-RuntimeDiagnosticBrokerSummary')
    boundary_doc=txt(root/'docs/SECURITY_BOUNDARY.md') if (root/'docs/SECURITY_BOUNDARY.md').is_file() else ''
    s.c('LBS-6 canonical security boundary document exists',(root/'docs/SECURITY_BOUNDARY.md').is_file())
    s.has('LBS-6 security document forbids free task names',boundary_doc,'No runtime API accepts a free Scheduled Task name.')
    s.has('LBS-6 security document preserves one-shot semantics',boundary_doc,'One-Shot Next Boot')
    s.has('LBS-6 runtime supports hardened TaskBroker schema',template,"$script:SupportedTaskBrokerVersions = @('0.2.13')")
    s.has('LBS-6 installer emits hardened TaskBroker schema',installer,"$version = '0.2.13'")
    s.has('LBS-6 installer emits fixed boundary marker',installer,"boundaryContract = 'fixed-task-v1'")
    s.no('LBS-6 runtime has no TaskName-based authorized invocation',taskbroker.lower(),'invoke-authorizedtask -taskname')
    s.has('LBS-6 runtime authorized runner is operation-only',taskbroker,"[ValidateSet('ManagerRefresh','FirmwareRefresh','BootNext','DefaultSet','DefaultClear')]")
    s.has('LBS-6 metadata contract is enforced',taskbroker,'function Test-TaskBrokerMetadataContract')
    s.has('LBS-6 target task names are derived',taskbroker,'function Get-TaskBrokerExpectedTargetTaskName')
    s.has('LBS-6 task ACL least-privilege replacement exists',installer,'function Get-TaskReadExecuteOnlySddl')
    s.has('LBS-6 task ACL rejects dangerous rights',installer,'$dangerousMask')
    s.no('LBS-6 GenericAll is not accepted as success',installer,'$hasAll =')
    s.has('LBS-6 ProgramData state is ACL-protected',installer,'function Protect-TaskBrokerStateDirectory')
    s.has('LBS-6 metadata file is ACL-protected',installer,'function Protect-TaskBrokerMetadataFile')
    s.has('v0.6.4.1 ACL predicate checks concrete write data',rights_predicate,'FileSystemRights]::WriteData')
    s.has('v0.6.4.1 ACL predicate checks append data',rights_predicate,'FileSystemRights]::AppendData')
    s.has('v0.6.4.1 ACL predicate checks ACL ownership mutation',rights_predicate,'FileSystemRights]::TakeOwnership')
    s.no('v0.6.4.1 state ACL validator does not use composite Modify mask',state_acl,'FileSystemRights]::Modify')
    s.has('v0.6.4.1 state ACL validator calls mutation predicate',state_acl,'Test-TaskBrokerRightsContainMutation -Rights $rights')
    s.has('v0.6.4.1 diagnostics report physical presence',broker_summary,'$present = [bool](Test-TaskBrokerInstallationPresent)')
    s.has('v0.6.4.1 diagnostics report metadata readability',broker_summary,'metadataReadable = $true')
    s.has('v0.6.4.1 diagnostics report compatibility separately',broker_summary,'compatible = $compatible')
    s.no('v0.6.4.1 diagnostics do not derive presence from trusted metadata',broker_summary,'$meta = Get-TaskBrokerMetadata')
    s.c('LBS-6 native TaskBroker boundary test exists',(root/'tests/Test-TaskBrokerBoundary.ps1').is_file())
    native_boundary=txt(root/'tests/Test-TaskBrokerBoundary.ps1')
    s.has('LBS-6 native boundary test runs in PS5.1 aggregate',txt(root/'tests/Test-WindowsPowerShell51.ps1'),'Test-TaskBrokerBoundary.ps1')
    s.has('v0.6.4.1 native regression accepts ReadAndExecute',native_boundary,'ReadAndExecute is accepted as non-mutating')
    s.has('v0.6.4.1 native regression rejects Modify',native_boundary,'Modify is rejected as mutating')
    s.has('v0.6.4.1 native regression rejects FullControl',native_boundary,'FullControl is rejected as mutating')
    s.no('LBS-6 keeps permanent displayorder mutation absent',tray,"'/set', '{fwbootmgr}', 'displayorder'")
    s.no('LBS-6 keeps custom SYSTEM EXE absent',installer,'LenovoBootMenuBroker.exe')
    return s.done()
if __name__=='__main__': raise SystemExit(main())
