# Lenovo Boot Selector - Functional Core: localization
# Pure/deterministic functions only. No script state, WinForms, filesystem, registry,
# network, process starts, Scheduled Tasks, or privileged broker access.

function Get-SupportedLocaleIdsCore {
    return @('en-US', 'de-DE')
}

function Resolve-LocaleIdCore {
    param([string]$Locale)

    $value = ([string]$Locale).Trim()
    foreach ($supported in @(Get-SupportedLocaleIdsCore)) {
        if ($value -and $value.Equals($supported, [System.StringComparison]::OrdinalIgnoreCase)) {
            return $supported
        }
    }
    return 'en-US'
}

function Get-LocalizationCatalogCore {
    return [ordered]@{
        'en-US' = [ordered]@{
            'Common.OK' = 'OK'
            'Common.Cancel' = 'Cancel'
            'Common.Close' = 'Close'
            'Common.TryAgain' = 'Please try again.'
            'Settings.Language' = 'Language'
            'Language.English' = 'English'
            'Language.German' = 'Deutsch'
            'Progress.StepOf' = 'Step {0} of {1}'
            'Storage.InternalSsdModel' = 'Internal SSD: {Model}'
            'Popup.HeaderUpdateAccessible' = 'Opens the dialog for the available app version.'
            'Status.BootTargetsRefreshing' = 'Boot targets are being refreshed in the background…'
            'Action.RefreshBootTargets' = 'Refresh boot targets'
            'Popup.NextBootSection' = 'NEXT BOOT'
            'Popup.Customize' = 'CUSTOMIZE'
            'Status.ScrollPositionFailed' = 'The scroll position could not be updated.'
            'Settings.Title' = 'SETTINGS'
            'Settings.Autostart' = 'Start with Windows'
            'Settings.DefaultTarget' = 'Default boot target'
            'Settings.NoDefaultTarget' = 'No default target'
            'Settings.DefaultTargetUnavailable' = 'Boot target unavailable'
            'Status.Checking' = 'Checking …'
            'Action.RestartWindows' = 'Restart Windows'
            'Status.NextTargetDefaultOrder' = 'Next target: default order'
            'Manage.Section' = 'ADJUST BOOT TARGETS'
            'Manage.Title' = 'CHANGES'
            'Manage.Hint' = 'Drag to sort · Click to show/hide'
            'Manage.SubHint' = 'Pencil to rename · Leave empty = original name'
            'Manage.Save' = 'Save changes'
            'Manage.StatusEditing' = 'Customize boot targets · Drag to sort · Click to show/hide · Pencil for display name'
            'Manage.StatusSaved' = 'Boot-target changes were saved.'
            'Manage.StatusDiscarded' = 'Changes were discarded.'
            'Autostart.Enabled' = 'Autostart is enabled.'
            'Autostart.Disabled' = 'Autostart is disabled.'
            'Autostart.ErrorHeading' = 'The setting could not be changed.'
            'Default.SaveErrorHeading' = 'The default boot target could not be saved.'
            'Default.SaveErrorMessage' = 'Please try again. If the problem persists, open Maintenance → Repair system functions.'
            'Status.NewBootTargetDetected' = 'New boot target detected · Reinitialize system functions.'
            'Status.BootTargetsChanged' = 'Boot targets changed · Reinitialize system functions.'
            'Status.SystemFunctionsRepairRequired' = 'System functions need to be repaired.'
            'Status.SystemFunctionsSetupRequired' = 'System functions need to be set up.'
            'Header.Refreshing' = 'Updating boot targets…'
            'Update.Available' = 'New app version available'
            'Tray.Open' = 'Open Lenovo Boot Selector'
            'Tray.Maintenance' = 'Maintenance'
            'Maintenance.Setup' = 'Set up system functions…'
            'Maintenance.Remove' = 'Remove system functions…'
            'Update.Check' = 'Check for new version…'
            'Update.Install' = 'Update app…'
            'Diagnostics.Save' = 'Save diagnostics…'
            'Boot.OtherTarget' = 'Other boot target'
            'Boot.OtherTargetTooltip' = 'Gray: other boot target'
            'Boot.MenuTitle' = 'Lenovo Boot Menu'
            'Boot.MenuSubtitle' = 'Open the boot menu on the next startup'
            'Boot.MenuTooltip' = 'Red: Lenovo Boot Menu'
            'Boot.Nvme1Title' = 'NVMe SSD 1'
            'Boot.Nvme2Title' = 'NVMe SSD 2'
            'Boot.NoDrive' = 'No drive detected'
            'Boot.InternalSsd' = 'Internal SSD'
            'Boot.SecondInternalSsd' = 'Second internal SSD'
            'Boot.InternalSsdTooltip' = 'Blue: internal SSD'
            'Boot.UsbTooltip' = 'Yellow: USB drive'
            'Boot.UsbChecking' = 'Checking USB drives …'
            'Boot.UsbCheckFailed' = 'USB drives could not be checked'
            'Boot.UsbBootMedium' = 'USB boot medium: {Model}'
            'Boot.UsbMultipleBoot' = 'Multiple possible USB boot media detected'
            'Boot.UsbNonBoot' = '{Model} detected · not detected as boot medium'
            'Boot.UsbMultipleNoBoot' = 'USB drives detected · no boot medium found'
            'Boot.UsbNone' = 'No USB drive connected'
            'Boot.UsbFddTitle' = 'USB floppy drive'
            'Boot.UsbFddSubtitle' = 'Boot from a USB floppy drive'
            'Boot.UsbCdTitle' = 'USB CD/DVD drive'
            'Boot.UsbCdSubtitle' = 'Boot from an optical USB drive'
            'Boot.PxeTitle' = 'Network boot'
            'Boot.PxeSubtitle' = 'Boot over the local network'
            'Boot.PxeTooltip' = 'Purple: network boot'
            'Boot.LenovoRecoveryTitle' = 'Lenovo recovery'
            'Boot.LenovoRecoverySubtitle' = 'Recovery over the network'
            'Boot.CyanTooltip' = 'Cyan: Lenovo or corporate network'
            'Boot.CorporateTitle' = 'Corporate network boot'
            'Boot.CorporateSubtitle' = 'Boot over the corporate network'
            'Boot.OtherDriveTitle' = 'Other drive'
            'Boot.OtherDriveSubtitle' = 'Other detected drive'
            'Boot.OtherDriveTooltip' = 'Gray: other drive'
            'Boot.OtherCdTitle' = 'Other CD/DVD drive'
            'Boot.OtherCdSubtitle' = 'Other optical boot drive'
            'Status.NextBootTarget' = 'Next boot: {Title}'
            'Status.NextBootSet' = 'Next boot target was set.'
            'Boot.ChangeErrorTitle' = 'Boot target could not be changed'
            'Boot.ChangeErrorHeading' = 'The selection was not applied.'
            'Boot.ChangeErrorMessage' = 'Please try again. If the problem persists, open Maintenance → Repair system functions.'
            'Manage.OrderChanged' = 'Order changed · Save applies the change.'
            'Manage.OriginalName' = 'Original name: {Name}'
            'Boot.MenuManageSubtitle' = 'Selection menu for the next boot target'
            'Manage.AliasRemoved' = 'Display name removed · Save applies the change.'
            'Manage.AliasChanged' = 'Display name changed · Save applies the change.'
            'Manage.AliasDiscarded' = 'Display-name change discarded.'
            'Common.Apply' = 'Apply'
            'Manage.OriginalNameHint' = 'Leave empty = original name'
            'Manage.EditAliasAccessible' = 'Change display name'
            'Manage.EditAliasStatus' = 'Edit display name · Enter applies · Esc discards · empty = original name'
            'Maintenance.Dialog.RemoveTitle' = 'Remove system functions'
            'Maintenance.Dialog.RemoveHeading' = 'Remove system functions?'
            'Maintenance.Dialog.RemoveBody' = "After this, Lenovo Boot Selector cannot change boot targets until setup is completed again.`r`n`r`nThe saved default boot target will be reset.`r`n`r`nYour existing boot targets, personal app settings, and autostart setting will be kept."
            'Maintenance.Action.Remove' = 'Remove'
            'Maintenance.Dialog.RepairTitle' = 'Repair system functions'
            'Maintenance.Dialog.RepairHeading' = 'System functions are already set up.'
            'Maintenance.Dialog.RepairBody' = 'Set them up again and repair them? Your boot targets and personal settings will be kept.'
            'Maintenance.Action.Repair' = 'Repair'
            'Maintenance.Dialog.MigrateHeading' = 'The setup needs to be updated.'
            'Maintenance.Dialog.MigrateBody' = 'An older or incomplete setup was found. Repair it so boot targets can be changed reliably again.'
            'Maintenance.Dialog.ReinitializeTitle' = 'Reinitialize system functions'
            'Maintenance.Dialog.ReinitializeHeading' = 'New boot target detected'
            'Maintenance.Dialog.ReinitializeBody' = 'Lenovo Boot Selector detected a change to the available boot targets. Reinitialize the system functions so the new boot target can be used safely. Your personal settings will be kept.'
            'Maintenance.Action.Reinitialize' = 'Reinitialize'
            'Maintenance.Dialog.SetupTitle' = 'Set up system functions'
            'Maintenance.Dialog.SetupHeading' = 'One-time setup required'
            'Maintenance.Dialog.SetupBody' = 'Lenovo Boot Selector requires a one-time Windows confirmation before it can change boot targets. After that, you can select boot targets without further confirmation.'
            'Maintenance.Action.Setup' = 'Set up'
            'Restart.DialogTitle' = 'Restart Windows'
            'Restart.Question' = 'Restart Windows now?'
            'Restart.NextTarget' = 'NEXT TARGET'
            'Restart.Action' = 'Restart'
            'Maintenance.Busy.Remove' = 'Removing system functions…'
            'Maintenance.Busy.Reinitialize' = 'Reinitializing system functions…'
            'Maintenance.Busy.Repair' = 'Repairing system functions…'
            'Maintenance.Busy.Setup' = 'Setting up system functions…'
            'Maintenance.Caption' = 'SYSTEM FUNCTIONS'
            'Maintenance.Panel.SetupHeading' = 'Set up system functions'
            'Maintenance.Panel.SetupMessage' = 'A one-time Windows confirmation is required before Lenovo Boot Selector can change boot targets.'
            'Maintenance.Panel.SetupHint' = 'Afterward, you can select boot targets without further confirmation.'
            'Maintenance.Panel.RepairHeading' = 'Repair system functions'
            'Maintenance.Panel.RepairMessage' = 'The existing setup is incomplete or needs to be updated.'
            'Maintenance.Panel.RepairHint' = 'Your personal settings will be kept.'
            'Maintenance.Panel.NewTargetHeading' = 'New boot target detected'
            'Maintenance.Panel.NewTargetMessage' = 'Lenovo Boot Selector detected a new boot target. Reinitialize the system functions so it can be used safely.'
            'Maintenance.Panel.TargetsChangedHeading' = 'Boot targets changed'
            'Maintenance.Panel.TargetsChangedMessage' = 'The available boot targets have changed. Reinitialize the system functions so the selection is complete again.'
            'Maintenance.Panel.BusyRemoveMessage' = 'The system functions are being removed safely. Please wait a moment.'
            'Maintenance.Panel.BusyReinitializeMessage' = 'Windows is setting up the system functions again for the changed boot targets. Please wait a moment.'
            'Maintenance.Panel.BusySetupMessage' = 'Windows is setting up the required system functions. Please wait a moment.'
            'Maintenance.Panel.BusyHint' = 'The app updates automatically when the operation is complete.'
            'Maintenance.SuccessRemovedTitle' = 'System functions removed'
            'Maintenance.SuccessRemovedHeading' = 'System functions were removed.'
            'Maintenance.SuccessRemovedMessage' = 'Boot targets can be changed again after you set up the system functions again.'
            'Maintenance.SuccessReinitializedTitle' = 'Reinitialized'
            'Maintenance.SuccessReinitializedHeading' = 'System functions were reinitialized.'
            'Maintenance.SuccessReinitializedMessage' = 'The detected boot target can now be used safely.'
            'Maintenance.SuccessReadyTitle' = 'System functions ready'
            'Maintenance.SuccessReadyHeading' = 'System functions are ready.'
            'Maintenance.SuccessReadyMessage' = 'Lenovo Boot Selector can now change boot targets.'
            'Update.SuccessTitle' = 'Update successful'
            'Update.SuccessHeading' = 'Lenovo Boot Selector v{Version} is installed.'
            'Update.FailureTitle' = 'Update failed'
            'Update.RestartFailureHeading' = 'The app could not be updated successfully.'
            'Update.AvailableHeading' = 'Lenovo Boot Selector v{Version} is available.'
            'Update.AvailableMessage' = 'You can install the new version now. You can also find the update later in the tray menu under Maintenance → Update app…'
            'Update.InstallNow' = 'Update now'
            'Update.CheckNoResult' = 'The update check did not return a result.'
            'Update.AvailableStatus' = 'New app version available: v{Version}'
            'Update.CurrentStatus' = 'Lenovo Boot Selector is up to date · v{Version}'
            'Update.NoNewTitle' = 'No new version'
            'Update.CurrentHeading' = 'Lenovo Boot Selector v{Version} is up to date.'
            'Update.NoNewMessage' = 'No newer version is currently available.'
            'Update.CheckFailedStatus' = 'Update check failed.'
            'Update.CheckFailedHeading' = 'Checking for a new version failed.'
            'Update.CheckStartFailed' = 'The update check could not be started.'
            'Update.CheckingStatus' = 'Checking for a new version…'
            'Update.InstallerStartFailed' = 'The update installer could not be started.'
            'Update.PrepareNoResult' = 'Update preparation did not return a result.'
            'Update.PrepareFailedHeading' = 'The app could not be updated.'
            'Update.NotPossibleTitle' = 'Update not possible'
            'Update.DirectoryNotWritableHeading' = 'The app folder is not writable.'
            'Update.DirectoryNotWritableMessage' = 'Move Lenovo Boot Selector to a folder that your user account can modify, then try again.'
            'Update.PrepareStartFailed' = 'Update preparation could not be started.'
            'Update.PreparingStatus' = 'Preparing update to v{Version}…'
            'Diagnostics.SavedTitle' = 'Diagnostics saved'
            'Diagnostics.SavedHeading' = 'The diagnostic package was created.'
            'Diagnostics.Location' = "Location:`r`n{Path}"
            'Diagnostics.ShowFolder' = 'Show in folder'
            'Diagnostics.NotSavedTitle' = 'Diagnostics not saved'
            'Diagnostics.NotSavedHeading' = 'The diagnostic package could not be created.'
            'Startup.AlreadyRunningTitle' = 'Lenovo Boot Selector is already running'
            'Startup.FailedTitle' = 'Lenovo Boot Selector could not be started'
            'Startup.AlreadyRunningBody' = 'The app is already open. Close this window and use the existing tray icon.'
            'Startup.FailedSavedBody' = "A problem occurred during startup.`r`nA diagnostic file was saved. You can restart the app or open the diagnostics."
            'Startup.FailedNoDiagnosticBody' = "A problem occurred during startup.`r`nThe diagnostic file could not be saved. You can restart the app."
            'Startup.DiagnosticFile' = 'Diagnostics: {Name}'
            'Startup.NoDiagnosticFile' = 'No diagnostic file is available.'
            'Startup.OpenDiagnostics' = 'Open diagnostics'
            'Startup.Retry' = 'Restart app'
            'Startup.FallbackError' = 'Lenovo Boot Selector could not be started.'
            'Startup.AlreadyRunningMessage' = 'Lenovo Boot Selector is already running.'
            'Tray.Exit' = 'Exit'
        }
        'de-DE' = [ordered]@{
            'Common.OK' = 'OK'
            'Common.Cancel' = 'Abbrechen'
            'Common.Close' = 'Schließen'
            'Common.TryAgain' = 'Bitte versuche es erneut.'
            'Settings.Language' = 'Sprache'
            'Language.English' = 'English'
            'Language.German' = 'Deutsch'
            'Progress.StepOf' = 'Schritt {0} von {1}'
            'Storage.InternalSsdModel' = 'Interne SSD: {Model}'
            'Popup.HeaderUpdateAccessible' = 'Öffnet den Dialog zur verfügbaren App-Version.'
            'Status.BootTargetsRefreshing' = 'Startziele werden im Hintergrund aktualisiert…'
            'Action.RefreshBootTargets' = 'Startziele aktualisieren'
            'Popup.NextBootSection' = 'NÄCHSTER START'
            'Popup.Customize' = 'ANPASSEN'
            'Status.ScrollPositionFailed' = 'Scrollposition konnte nicht aktualisiert werden.'
            'Settings.Title' = 'EINSTELLUNGEN'
            'Settings.Autostart' = 'Mit Windows starten'
            'Settings.DefaultTarget' = 'Standard-Startziel'
            'Settings.NoDefaultTarget' = 'Kein Standardziel'
            'Settings.DefaultTargetUnavailable' = 'Nicht verfügbares Startziel'
            'Status.Checking' = 'Wird geprüft …'
            'Action.RestartWindows' = 'Windows neu starten'
            'Status.NextTargetDefaultOrder' = 'Nächstes Ziel: Standardreihenfolge'
            'Manage.Section' = 'STARTZIELE ANPASSEN'
            'Manage.Title' = 'ÄNDERUNGEN'
            'Manage.Hint' = 'Ziehen zum Sortieren · Klicken zum Ein-/Ausblenden'
            'Manage.SubHint' = 'Stift zum Umbenennen · Leer lassen = Originalname'
            'Manage.Save' = 'Änderungen speichern'
            'Manage.StatusEditing' = 'Startziele anpassen · Ziehen zum Sortieren · Klicken zum Ein-/Ausblenden · Stift für Anzeigename'
            'Manage.StatusSaved' = 'Änderungen an den Startzielen wurden gespeichert.'
            'Manage.StatusDiscarded' = 'Änderungen wurden verworfen.'
            'Autostart.Enabled' = 'Autostart ist aktiviert.'
            'Autostart.Disabled' = 'Autostart ist deaktiviert.'
            'Autostart.ErrorHeading' = 'Die Einstellung konnte nicht geändert werden.'
            'Default.SaveErrorHeading' = 'Das Standard-Startziel konnte nicht gespeichert werden.'
            'Default.SaveErrorMessage' = 'Bitte versuche es erneut. Falls das Problem bestehen bleibt, öffne Wartung → Systemfunktionen reparieren.'
            'Status.NewBootTargetDetected' = 'Neues Startziel erkannt · Systemfunktionen neu initialisieren.'
            'Status.BootTargetsChanged' = 'Startziele geändert · Systemfunktionen neu initialisieren.'
            'Status.SystemFunctionsRepairRequired' = 'Systemfunktionen müssen repariert werden.'
            'Status.SystemFunctionsSetupRequired' = 'Systemfunktionen müssen eingerichtet werden.'
            'Header.Refreshing' = 'Aktualisiere Bootziele…'
            'Update.Available' = 'Neue App-Version verfügbar'
            'Tray.Open' = 'Lenovo Boot Selector öffnen'
            'Tray.Maintenance' = 'Wartung'
            'Maintenance.Setup' = 'Systemfunktionen einrichten…'
            'Maintenance.Remove' = 'Systemfunktionen entfernen…'
            'Update.Check' = 'Auf neue Version prüfen…'
            'Update.Install' = 'App aktualisieren…'
            'Diagnostics.Save' = 'Diagnose speichern…'
            'Boot.OtherTarget' = 'Weiteres Startziel'
            'Boot.OtherTargetTooltip' = 'Grau: weiteres Startziel'
            'Boot.MenuTitle' = 'Lenovo Boot-Menü'
            'Boot.MenuSubtitle' = 'Beim nächsten Start das Boot-Menü öffnen'
            'Boot.MenuTooltip' = 'Rot: Lenovo Boot-Menü'
            'Boot.Nvme1Title' = 'NVMe-SSD 1'
            'Boot.Nvme2Title' = 'NVMe-SSD 2'
            'Boot.NoDrive' = 'Kein Laufwerk erkannt'
            'Boot.InternalSsd' = 'Interne SSD'
            'Boot.SecondInternalSsd' = 'Zweite interne SSD'
            'Boot.InternalSsdTooltip' = 'Blau: interne SSD'
            'Boot.UsbTooltip' = 'Gelb: USB-Laufwerk'
            'Boot.UsbChecking' = 'USB-Laufwerke werden geprüft …'
            'Boot.UsbCheckFailed' = 'USB-Laufwerke konnten nicht geprüft werden'
            'Boot.UsbBootMedium' = 'USB-Startmedium: {Model}'
            'Boot.UsbMultipleBoot' = 'Mehrere mögliche USB-Startmedien erkannt'
            'Boot.UsbNonBoot' = '{Model} erkannt · nicht als Startmedium erkannt'
            'Boot.UsbMultipleNoBoot' = 'USB-Laufwerke erkannt · kein Startmedium gefunden'
            'Boot.UsbNone' = 'Kein USB-Laufwerk angeschlossen'
            'Boot.UsbFddTitle' = 'USB-Diskettenlaufwerk'
            'Boot.UsbFddSubtitle' = 'Start von einem USB-Floppy-Laufwerk'
            'Boot.UsbCdTitle' = 'USB-CD/DVD-Laufwerk'
            'Boot.UsbCdSubtitle' = 'Start von einem optischen USB-Laufwerk'
            'Boot.PxeTitle' = 'Netzwerkstart'
            'Boot.PxeSubtitle' = 'Start über das lokale Netzwerk'
            'Boot.PxeTooltip' = 'Violett: Netzwerkstart'
            'Boot.LenovoRecoveryTitle' = 'Lenovo Wiederherstellung'
            'Boot.LenovoRecoverySubtitle' = 'Wiederherstellung über das Netzwerk'
            'Boot.CyanTooltip' = 'Cyan: Lenovo- oder Firmen-Netzwerk'
            'Boot.CorporateTitle' = 'Firmen-Netzwerkstart'
            'Boot.CorporateSubtitle' = 'Start über das Firmennetzwerk'
            'Boot.OtherDriveTitle' = 'Weiteres Laufwerk'
            'Boot.OtherDriveSubtitle' = 'Weiteres erkanntes Laufwerk'
            'Boot.OtherDriveTooltip' = 'Grau: weiteres Laufwerk'
            'Boot.OtherCdTitle' = 'Weiteres CD/DVD-Laufwerk'
            'Boot.OtherCdSubtitle' = 'Anderes optisches Startlaufwerk'
            'Status.NextBootTarget' = 'Nächster Start: {Title}'
            'Status.NextBootSet' = 'Nächstes Startziel wurde gesetzt.'
            'Boot.ChangeErrorTitle' = 'Startziel konnte nicht geändert werden'
            'Boot.ChangeErrorHeading' = 'Die Auswahl wurde nicht übernommen.'
            'Boot.ChangeErrorMessage' = 'Bitte versuche es erneut. Falls das Problem bestehen bleibt, öffne Wartung → Systemfunktionen reparieren.'
            'Manage.OrderChanged' = 'Reihenfolge geändert · Speichern übernimmt die Änderung.'
            'Manage.OriginalName' = 'Originalname: {Name}'
            'Boot.MenuManageSubtitle' = 'Auswahlmenü für das nächste Startziel'
            'Manage.AliasRemoved' = 'Anzeigename entfernt · Speichern übernimmt die Änderung.'
            'Manage.AliasChanged' = 'Anzeigename geändert · Speichern übernimmt die Änderung.'
            'Manage.AliasDiscarded' = 'Änderung am Anzeigenamen verworfen.'
            'Common.Apply' = 'Übernehmen'
            'Manage.OriginalNameHint' = 'Leer lassen = Originalname'
            'Manage.EditAliasAccessible' = 'Anzeigename ändern'
            'Manage.EditAliasStatus' = 'Anzeigename bearbeiten · Enter übernimmt · Esc verwirft · leer = Originalname'
            'Maintenance.Dialog.RemoveTitle' = 'Systemfunktionen entfernen'
            'Maintenance.Dialog.RemoveHeading' = 'Systemfunktionen wirklich entfernen?'
            'Maintenance.Dialog.RemoveBody' = "Danach kann Lenovo Boot Selector keine Startziele mehr ändern, bis die Einrichtung erneut durchgeführt wird.`r`n`r`nDas gespeicherte Standard-Startziel wird zurückgesetzt.`r`n`r`nErhalten bleiben deine vorhandenen Startziele, persönlichen App-Einstellungen und die Autostart-Einstellung."
            'Maintenance.Action.Remove' = 'Entfernen'
            'Maintenance.Dialog.RepairTitle' = 'Systemfunktionen reparieren'
            'Maintenance.Dialog.RepairHeading' = 'Die Systemfunktionen sind bereits eingerichtet.'
            'Maintenance.Dialog.RepairBody' = 'Möchtest du sie erneut einrichten und reparieren? Deine Startziele und persönlichen Einstellungen bleiben dabei erhalten.'
            'Maintenance.Action.Repair' = 'Reparieren'
            'Maintenance.Dialog.MigrateHeading' = 'Die Einrichtung muss aktualisiert werden.'
            'Maintenance.Dialog.MigrateBody' = 'Eine ältere oder unvollständige Einrichtung wurde gefunden. Repariere sie, damit Startziele wieder zuverlässig geändert werden können.'
            'Maintenance.Dialog.ReinitializeTitle' = 'Systemfunktionen neu initialisieren'
            'Maintenance.Dialog.ReinitializeHeading' = 'Neues Startziel erkannt'
            'Maintenance.Dialog.ReinitializeBody' = 'Lenovo Boot Selector hat eine Änderung an den verfügbaren Startzielen erkannt. Initialisiere die Systemfunktionen neu, damit das neue Startziel sicher verwendet werden kann. Deine persönlichen Einstellungen bleiben erhalten.'
            'Maintenance.Action.Reinitialize' = 'Neu initialisieren'
            'Maintenance.Dialog.SetupTitle' = 'Systemfunktionen einrichten'
            'Maintenance.Dialog.SetupHeading' = 'Einmalige Einrichtung erforderlich'
            'Maintenance.Dialog.SetupBody' = 'Damit Lenovo Boot Selector Startziele ändern kann, ist einmalig eine Windows-Bestätigung erforderlich. Danach kannst du Startziele ohne weitere Bestätigung auswählen.'
            'Maintenance.Action.Setup' = 'Einrichten'
            'Restart.DialogTitle' = 'Windows neu starten'
            'Restart.Question' = 'Windows jetzt neu starten?'
            'Restart.NextTarget' = 'NÄCHSTES ZIEL'
            'Restart.Action' = 'Neu starten'
            'Maintenance.Busy.Remove' = 'Systemfunktionen werden entfernt…'
            'Maintenance.Busy.Reinitialize' = 'Systemfunktionen werden neu initialisiert…'
            'Maintenance.Busy.Repair' = 'Systemfunktionen werden repariert…'
            'Maintenance.Busy.Setup' = 'Systemfunktionen werden eingerichtet…'
            'Maintenance.Caption' = 'SYSTEMFUNKTIONEN'
            'Maintenance.Panel.SetupHeading' = 'Systemfunktionen einrichten'
            'Maintenance.Panel.SetupMessage' = 'Damit Lenovo Boot Selector Startziele ändern kann, ist einmalig eine Windows-Bestätigung erforderlich.'
            'Maintenance.Panel.SetupHint' = 'Danach kannst du Startziele ohne weitere Bestätigung auswählen.'
            'Maintenance.Panel.RepairHeading' = 'Systemfunktionen reparieren'
            'Maintenance.Panel.RepairMessage' = 'Die vorhandene Einrichtung ist unvollständig oder muss aktualisiert werden.'
            'Maintenance.Panel.RepairHint' = 'Deine persönlichen Einstellungen bleiben dabei erhalten.'
            'Maintenance.Panel.NewTargetHeading' = 'Neues Startziel erkannt'
            'Maintenance.Panel.NewTargetMessage' = 'Lenovo Boot Selector hat ein neues Startziel erkannt. Initialisiere die Systemfunktionen neu, damit es sicher verwendet werden kann.'
            'Maintenance.Panel.TargetsChangedHeading' = 'Startziele wurden geändert'
            'Maintenance.Panel.TargetsChangedMessage' = 'Die verfügbaren Startziele haben sich geändert. Initialisiere die Systemfunktionen neu, damit die Auswahl wieder vollständig passt.'
            'Maintenance.Panel.BusyRemoveMessage' = 'Die Systemfunktionen werden sicher entfernt. Bitte warte einen Moment.'
            'Maintenance.Panel.BusyReinitializeMessage' = 'Windows richtet die Systemfunktionen für die geänderten Startziele neu ein. Bitte warte einen Moment.'
            'Maintenance.Panel.BusySetupMessage' = 'Windows richtet die benötigten Systemfunktionen ein. Bitte warte einen Moment.'
            'Maintenance.Panel.BusyHint' = 'Die App wird nach Abschluss automatisch aktualisiert.'
            'Maintenance.SuccessRemovedTitle' = 'Systemfunktionen entfernt'
            'Maintenance.SuccessRemovedHeading' = 'Systemfunktionen wurden entfernt.'
            'Maintenance.SuccessRemovedMessage' = 'Startziele können wieder geändert werden, nachdem du die Systemfunktionen erneut eingerichtet hast.'
            'Maintenance.SuccessReinitializedTitle' = 'Neu initialisiert'
            'Maintenance.SuccessReinitializedHeading' = 'Systemfunktionen wurden neu initialisiert.'
            'Maintenance.SuccessReinitializedMessage' = 'Das erkannte Startziel kann jetzt sicher verwendet werden.'
            'Maintenance.SuccessReadyTitle' = 'Systemfunktionen bereit'
            'Maintenance.SuccessReadyHeading' = 'Systemfunktionen sind bereit.'
            'Maintenance.SuccessReadyMessage' = 'Lenovo Boot Selector kann jetzt Startziele ändern.'
            'Update.SuccessTitle' = 'Update erfolgreich'
            'Update.SuccessHeading' = 'Lenovo Boot Selector v{Version} ist installiert.'
            'Update.FailureTitle' = 'Update fehlgeschlagen'
            'Update.RestartFailureHeading' = 'Die App konnte nicht erfolgreich aktualisiert werden.'
            'Update.AvailableHeading' = 'Lenovo Boot Selector v{Version} ist verfügbar.'
            'Update.AvailableMessage' = 'Du kannst die neue Version jetzt direkt installieren. Später findest du die Aktualisierung im Tray-Menü unter Wartung → App aktualisieren…'
            'Update.InstallNow' = 'Jetzt aktualisieren'
            'Update.CheckNoResult' = 'Die Update-Prüfung hat kein Ergebnis geliefert.'
            'Update.AvailableStatus' = 'Neue App-Version verfügbar: v{Version}'
            'Update.CurrentStatus' = 'Lenovo Boot Selector ist aktuell · v{Version}'
            'Update.NoNewTitle' = 'Keine neue Version'
            'Update.CurrentHeading' = 'Lenovo Boot Selector v{Version} ist aktuell.'
            'Update.NoNewMessage' = 'Es ist derzeit keine neuere Version verfügbar.'
            'Update.CheckFailedStatus' = 'Update-Prüfung fehlgeschlagen.'
            'Update.CheckFailedHeading' = 'Die Prüfung auf eine neue Version ist fehlgeschlagen.'
            'Update.CheckStartFailed' = 'Die Update-Prüfung konnte nicht gestartet werden.'
            'Update.CheckingStatus' = 'Auf neue Version wird geprüft…'
            'Update.InstallerStartFailed' = 'Update-Installer konnte nicht gestartet werden.'
            'Update.PrepareNoResult' = 'Die Update-Vorbereitung hat kein Ergebnis geliefert.'
            'Update.PrepareFailedHeading' = 'Die App konnte nicht aktualisiert werden.'
            'Update.NotPossibleTitle' = 'Update nicht möglich'
            'Update.DirectoryNotWritableHeading' = 'Der App-Ordner ist nicht beschreibbar.'
            'Update.DirectoryNotWritableMessage' = 'Verschiebe Lenovo Boot Selector in einen Ordner, den dein Benutzerkonto ändern darf, und versuche es erneut.'
            'Update.PrepareStartFailed' = 'Update-Vorbereitung konnte nicht gestartet werden.'
            'Update.PreparingStatus' = 'Update auf v{Version} wird vorbereitet…'
            'Diagnostics.SavedTitle' = 'Diagnose gespeichert'
            'Diagnostics.SavedHeading' = 'Das Diagnosepaket wurde erstellt.'
            'Diagnostics.Location' = "Speicherort:`r`n{Path}"
            'Diagnostics.ShowFolder' = 'Im Ordner anzeigen'
            'Diagnostics.NotSavedTitle' = 'Diagnose nicht gespeichert'
            'Diagnostics.NotSavedHeading' = 'Das Diagnosepaket konnte nicht erstellt werden.'
            'Startup.AlreadyRunningTitle' = 'Lenovo Boot Selector läuft bereits'
            'Startup.FailedTitle' = 'Lenovo Boot Selector konnte nicht gestartet werden'
            'Startup.AlreadyRunningBody' = 'Die App ist bereits geöffnet. Schließe dieses Fenster und verwende das vorhandene Tray-Symbol.'
            'Startup.FailedSavedBody' = "Beim Start ist ein Problem aufgetreten.`r`nEine Diagnose wurde gespeichert. Du kannst die App erneut starten oder die Diagnose öffnen."
            'Startup.FailedNoDiagnosticBody' = "Beim Start ist ein Problem aufgetreten.`r`nDie Diagnose konnte nicht gespeichert werden. Du kannst die App erneut starten."
            'Startup.DiagnosticFile' = 'Diagnose: {Name}'
            'Startup.NoDiagnosticFile' = 'Keine Diagnose-Datei verfügbar.'
            'Startup.OpenDiagnostics' = 'Diagnose öffnen'
            'Startup.Retry' = 'Erneut starten'
            'Startup.FallbackError' = 'Lenovo Boot Selector konnte nicht gestartet werden.'
            'Startup.AlreadyRunningMessage' = 'Lenovo Boot Selector läuft bereits.'
            'Tray.Exit' = 'Beenden'
        }
    }
}

function Get-LocalizationKeySetCore {
    param([string]$Locale = 'en-US')

    $resolved = Resolve-LocaleIdCore -Locale $Locale
    $catalogs = Get-LocalizationCatalogCore
    return @($catalogs[$resolved].Keys | ForEach-Object { [string]$_ } | Sort-Object)
}

function Test-LocalizationCatalogParityCore {
    $reference = @(Get-LocalizationKeySetCore -Locale 'en-US')
    foreach ($locale in @(Get-SupportedLocaleIdsCore)) {
        $keys = @(Get-LocalizationKeySetCore -Locale $locale)
        if ($keys.Count -ne $reference.Count) { return $false }
        for ($i = 0; $i -lt $reference.Count; $i++) {
            if ($keys[$i] -ne $reference[$i]) { return $false }
        }
    }
    return $true
}

function Get-LocalizedStringCore {
    param(
        [Parameter(Mandatory=$true)][string]$Key,
        [string]$Locale = 'en-US',
        [object[]]$Arguments,
        [System.Collections.IDictionary]$Values
    )

    $resolved = Resolve-LocaleIdCore -Locale $Locale
    $catalogs = Get-LocalizationCatalogCore
    $active = $catalogs[$resolved]
    $english = $catalogs['en-US']

    if ($active.Contains($Key)) {
        $text = [string]$active[$Key]
    }
    elseif ($english.Contains($Key)) {
        $text = [string]$english[$Key]
    }
    else {
        return $Key
    }

    if ($Values) {
        foreach ($name in @($Values.Keys | ForEach-Object { [string]$_ } | Sort-Object)) {
            $text = $text.Replace(('{' + $name + '}'), [string]$Values[$name])
        }
    }

    if ($null -ne $Arguments -and @($Arguments).Count -gt 0) {
        try { $text = $text -f @($Arguments) } catch { }
    }
    return $text
}
